config/routes.rb
Rails.application.routes.draw do

	post 'attendances', to: 'attendances#create'
  get 'events/new'
  get 'events/show'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
	resources :users, only: [:new, :create, :show]
	resources :events, only: [:new, :create, :show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  	
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, class_name: 'User'
	has_many :attendances
	has_many :attendees, through: :attendances, source: :user

	def self.future
		where("date > ?", Time.now)
	end

	def self.past
		where("date <= ?", Time.now)
	end
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true 

	has_many :events, foreign_key: 'creator_id'
	has_many :attendances
	has_many :attended_events, through: :attendances, source: :event


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	def create
		attendance = current_user.attendances.build(event_id: params[:event_id] )
		if attendance.save 
			redirect_to user_path(current_user)
		else
			redirect_to events_path
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new
  end

  def create
  	if logged_in?
  		event = current_user.events.new(event_params)
  		if event.save
  			redirect_to events_path
  		else
  			render 'new'
  		end
  	else
  		redirect_to login_path
  	end
  end

  def show
  	@event = Event.find(params[:id])
  end

	def index	
		@events = Event.all
	end

  private

  def event_params
  	params.require(:event).permit(:title, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user =User.find_by(email: params[:session][:email])
  	if user 
  		@current_user = user
  		session[:user_id] = user.id
  		redirect_to user_path(user)
  	else
  		render
  		'new'
  	end
  end

  def destroy
  	@current_user = nil
  	session.delete(:user_id)
  	redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@events = @user.events
	end

	private
		def user_params
			params.require(:user).permit(:user, :email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		if user = @current_user
			user
		elsif user_id = session[:user_id]
			user = User.find(user_id)
		else
			nil
		end
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>
<h3>Upcomin events</h3>
<ul><% @events.future.each do |event|%>
	<li>Event: <%= link_to event.title, event_path(event)%>, Location: <%= event.location %>, Date: <%= event.date %>, Creator: <%= event.creator.name %>, <%= link_to "Join event", attendances_path(event_id: event.id), method: 'post' %> </li>
	<% end %>
</ul>

<h3>Past Events</h3>

<ul><% @events.past.each do |event|%>
	<li>Event: <%= link_to event.title, event_path(event)%>, Location: <%= event.location %>, Date: <%= event.date %>, Creator: <%= event.creator.name %>, <%= link_to "Join event", attendances_path(event_id: event.id), method: 'post' %> </li>
	<% end %>
</ul>

app/views/events/new.html.erb
<h1>New event</h1>
<%= form_for @event, url: events_path do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<%= f.submit "New Event" %>

<% end %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Event: <%= @event.title%>, Location: <%= @event.location %>, Date: <%= @event.date %>,Creator: <%= @event.creator.name%></p>
<h3>Atendees</h3>
<% if @event.attendees %>
	<ul>
	<% @event.attendees.each do |attendee| %>
		<li><%= attendee.name %></li>
	<% end %>
	</ul>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RlsPrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% unless logged_in? %>
        <%= link_to "Login", login_path %>

      <% else %>
        <%= link_to "Log-out", logout_path, method: 'delete'%>
        <%= link_to current_user.name, user_path(current_user) %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |f|%>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1>User Show</h1>
<p>User: <%= @user.name %>, Email: <%= @user.email %> </p> 
<h3>Events Created</h3>
<% if @user.events %>
	<ul> 
	<% @user.events.each do |event| %>
		<li>Event:<%= event.title%>, Date: <%= event.date %> </li>
	<% end %>
	</ul>
<% end %>

<h3>Upcoming Events</h3>
<% if @user.attended_events.future %>
	<ul>
	<% @user.attended_events.future.each do |event| %>
		<li><%= event.title %></li>
	<% end %>
	</ul>
<% end %>

<h3>Past Events</h3>
<% if @user.attended_events.past %>
	<ul>
	<% @user.attended_events.past.each do |event| %>
		<li><%= event.title %></li>
	<% end %>
	</ul>
<% end %>	